# Generated by Django 3.2.7 on 2021-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist_app', '0002_tasklist_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='Person',
            new_name='person',
        ),
    ]
